<?php
// $Id$
/**
 * @file
 * Presents users with an option to create another node of the same type after a
 * node is added.
 */
/**
 * Implementation of hook_help().
 */
function addanother_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#addanother":
      $output = '<p>'.  t("Presents users with an option to create another node of the same type after a node is added.") .'</p>';
      return $output;
    case 'admin/settings/addanother':
      $output = 'Here you can select the content types for which an <em>"Add another..."</em> message will be displayed. After creating a new content node, users with the <a href="@addanother_perm">enable add another</a> permission will receive a message allowing them to add another content node of the same type.';
      return '<p>'. t($output, array(
        '@addanother_perm' => url('admin/user/permissions', array('fragment' => 'module-addanother')),
      )) .'</p>';
  }
}
/**
 * Implementation of hook_perm().
 */
function addanother_perm() {
  return array('enable add another');
}
/**
 * Implementation of hook_menu().
 */
function addanother_menu() {
  $items = array();
  $items['admin/settings/addanother'] = array(
    'title' => 'Add Another',
    'description' => 'Modify which node types display the Add Another message.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('addanother_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}
/**
 * This function sets up the admin/settings/addanother settings page.
 */
function addanother_admin() {
  $form['addanother_nodetypes'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Enable Add Another for these content types'),
    '#options' => node_get_types('names'),
    '#default_value' => variable_get('addanother_nodetypes', array()),
    '#description' => 'An <em>Add Another</em> message will be shown after creating these content types',
  );
  return system_settings_form($form);
}
/**
 * Implementation of hook_nodeapi().
 */
function addanother_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'insert':
      $allowed_nodetypes = variable_get('addanother_nodetypes', array());
      if (user_access('enable add another') && $allowed_nodetypes[$node->type]) {
        drupal_set_message(t('Add another <a href="@typeurl">%type</a>.', array(
          '@typeurl' => url('node/add/'. str_replace('_', '-', $node->type)),
          '%type' => node_get_types('name', $node)
          )));
      }
      break;
  }
}
